apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: kubeproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '0'
              memory: '0'
            limits:
              cpu: '256'
              memory: 11400G

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: kubeproject
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: nginx
